import { Theme } from "theme.slint";
import { FluentIcon } from "icons.slint";
import { AccentButton } from "components/accent_button.slint";
import { InfoBadge, BadgeKind } from "components/info_badge.slint";
import { Card } from "components/card.slint";
import { TextField } from "components/text_field.slint";
import { NumberBox } from "components/number_box.slint";
import { ComboBox } from "components/combo_box.slint";
import { CheckBox } from "components/checkbox.slint";
import { ToggleSwitch } from "components/toggle_switch.slint";
import { Picker } from "../picker/picker.slint";

export { Theme, FluentIcon, AccentButton, InfoBadge, BadgeKind, Card, TextField, NumberBox, ComboBox, CheckBox, ToggleSwitch, Picker }

export component Settings inherits Window {
    preferred-width: 1100px;
    preferred-height: 760px;
    title: "WinAssoc 設定";
    background: Theme.current.bg-mica;
}
