import { Theme } from "theme.slint";
import { FluentIcon } from "icons.slint";
import { AccentButton } from "components/accent_button.slint";
import { InfoBadge, BadgeKind } from "components/info_badge.slint";
import { Card } from "components/card.slint";
import { Picker } from "../picker/picker.slint";

export { Theme, FluentIcon, AccentButton, InfoBadge, BadgeKind, Card, Picker }

export component Settings inherits Window {
    preferred-width: 1100px;
    preferred-height: 760px;
    title: "WinAssoc 設定";
    background: Theme.current.bg-mica;
}
