import { Theme } from "../theme.slint";
import { FluentIcon } from "../icons.slint";
import { AccentButton } from "accent_button.slint";

export component CommandBar inherits Rectangle {
    in property <bool> dirty: false;
    in property <string> theme-icon: FluentIcon.system;
    callback refresh-clicked();
    callback save-clicked();
    callback apply-clicked();
    callback theme-clicked();
    height: 32px;
    background: transparent;
    HorizontalLayout {
        padding-right: Theme.spacing-s * 1px;
        spacing: Theme.spacing-xs * 1px;
        width: parent.width;
        alignment: end;
    }
}