import { Theme } from "../theme.slint";
import { FluentIcon } from "../icons.slint";

export component NumberBox inherits Rectangle {
    in property <string> label: "";
    in-out property <int> value: 0;
    in property <int> min: 0;
    in property <int> max: 100000;
    in property <int> step: 1;
    height: 32px;
    border-radius: Theme.radius-control * 1px;
    background: Theme.current.control-default;
    border-width: 1px;
    border-color: Theme.current.control-stroke;
    HorizontalLayout {
        padding-left: Theme.spacing-m * 1px;
        padding-right: 4px;
        TextInput {
            text: root.value;
            input-type: InputType.number;
            font-family: Theme.font-family;
            font-size: 14px;
            color: Theme.current.text-primary;
            vertical-alignment: center;
            width: parent.width - 48px;
            height: parent.height;
            accepted => {
                if (self.text.to-float() >= root.min && self.text.to-float() <= root.max) {
                    root.value = self.text.to-float();
                } else {
                    self.text = root.value;
                }
            }
        }
        VerticalLayout {
            spacing: 0px;
            Rectangle {
                height: 16px;
                width: 16px;
                background: transparent;
                TouchArea {
                    width: 100%;
                    height: 100%;
                    clicked => { root.value = Math.min(root.value + root.step, root.max); }
                }
                Text {
                    text: FluentIcon.chevron-up;
                    font-family: "Segoe Fluent Icons, Segoe MDL2 Assets";
                    font-size: 12px;
                    color: Theme.current.text-secondary;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    width: parent.width;
                    height: parent.height;
                }
            }
            Rectangle {
                height: 16px;
                width: 16px;
                background: transparent;
                TouchArea {
                    width: 100%;
                    height: 100%;
                    clicked => { root.value = Math.max(root.value - root.step, root.min); }
                }
                Text {
                    text: FluentIcon.chevron-down;
                    font-family: "Segoe Fluent Icons, Segoe MDL2 Assets";
                    font-size: 12px;
                    color: Theme.current.text-secondary;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    width: parent.width;
                    height: parent.height;
                }
            }
        }
    }
}
