import { Theme } from "../theme.slint";

export component TextField inherits Rectangle {
    in property <string> label: "";
    in property <string> placeholder: "";
    in property <string> error: "";
    in-out property <string> value <=> input.text;
    callback accepted(string);
    callback edited(string);
    horizontal-stretch: 1;
    height: 32px;
    border-radius: Theme.radius-control * 1px;
    background: Theme.current.control-default;
    border-width: 1px;
    border-color: root.error != "" ? Theme.current.system-critical : Theme.current.control-stroke;
    clip: true;
    input := TextInput {
        x: Theme.spacing-m * 1px;
        width: parent.width - Theme.spacing-m * 2 * 1px;
        height: 100%;
        font-family: Theme.font-family;
        font-size: 14px;
        color: Theme.current.text-primary;
        vertical-alignment: center;
        single-line: true;
        wrap: no-wrap;
        accepted => { root.accepted(self.text); }
        edited => { root.edited(self.text); }
    }
}
